/* 
  ----------
    Help provide pre-defined comment selection for report commenting
  ----------
*/

export const comments = {
  teacher: [
    "He is responsible and well behaved",
    "He is responsible and well behaved",
    "He is courteous and shows good manners",
    "He is responsible and hardworking",
    "He is well behaved and focused",
    "He is responsible and well behaved",
    "He is well behaved and dutiful",
    "He is gentle and well behaved",
    "He is courteous and shows good manners",
    "He is responsible, hardworking and shows good manners",
    "He is well behaved and dutiful",
    "He is well behaved and shows good manner",
    "He is friendly and respectful but has divided attention.",
    "He is energetic and active in class but too confident.",
    "He needs to be determined and purpose minded",
    "He has calmed down this term unlike his energetic behaviours.",
    "He is very active in class but needs to improve on his handwriting",
    "He is responsible and obedient but fearful.",
    "He is friendly and ready to learn",
    "He is active but carefree about the needful.",
    "He is simple and quiet but needs to improve on his ",
    "He is social and energetic but disrespectful.",
    "He has leadership traits coupled with godliness, but needs to work harder.",
    "A responsible and courteous boy.",
    "He is trying to improve and he can achieve it.",
    "He is sharp and purpose minded.",
    "She is responsible and well behaved",	 
    "She is well behaved and hardworking",
    "She is responsible and dutiful",
    "She is well behaved and shows good manners",
    "She is couteous and hardworking",
    "She is well behaved and shows good manners",
    "She is responsible and focused",
    "She is dutiful and well behaved",
    "She is well behaved and focused",
    "She is responsible and gentle",
    "She is couteous and shows good manners",
    "She is responsible, gentle and focused",
    "She is well behaved and focused",
    "She is reponsible and shows good manners",
    "She is well behaved and dutiful",
    "She is reponsible and well behaved",
    "She is studious and ready to learn.",
    "She is energetic but dislikes corrections.",
    "She always tries to know but her effor is not sufficient. She needs extra support.",
    "She is calm, simple and ready to improve always.",
    "She needs to work on her social skills.",
    "She is calm, simple and neatly dress always.",
    "She is quiet and well behaved.",
    "She is always neat and smart.",
    "She takes everything simple and carefree about studies.",
    "She is quiet and well behaved.",
    "She has calmed down this term unlike her energetic behaviours.",
    "She is quiet and serious with her studies",
    "She is active in class but comes late to school.",
    "She is energetic and serious with her studies.",
    "She is quiet and friendly. You can still improve on your studies",
    "She is reserved and needed to be active to studies."
  ],
  principal: [
    "A good result",	
    "A fair result work harder",	
    "An encouraging result, put more effort",	
    "Good result but improve on your weak subject",	
    "Fair result but needs to improve on your weak subject",	
    "A weak result, work harder",	
    "A weak result",	
    "Good result , keep it up",	
    "Good result, put more effort",	
    "A good result, work harder",	
    "You need to work harder",	
    "Weak result, there is room for improvement",	
    "Good performance, keep it up.",	
    "A good result but you can do better",	
    "A brilliant result. Keep the fire burning."	
  ]
}